#!/bin/sh

set -e

if [ "$1" = "configure" ] ; then
	update-alternatives --install /usr/bin/oslo_debug_helper		oslo_debug_helper		/usr/bin/python3-oslo_debug_helper 200
	update-alternatives --install /usr/bin/oslo_run_pre_release_tests	oslo_run_pre_release_tests	/usr/bin/python3-oslo_run_pre_release_tests 200
	update-alternatives --install /usr/bin/oslo_run_cross_tests		oslo_run_cross_tests		/usr/bin/python3-oslo_run_cross_tests 200
fi

#DEBHELPER#

exit 0
